FROM faddat/sos-lite

# Add seeds and such after doing gaia.
# I will prototype the rest of this on gaia.
RUN echo wizechain1 > /etc/hostname && \
		pacman -Syyu --noconfirm docker-compose zerotier-one
#		echo "docker run nicknailers69/wizechain1" >> /usr/local/bin/firstboot.sh
# TODO: docker-compose
